### ISSUE TITLE
Maybe modal can pass a partial template as modal body.

### ISSUE THREAD

**Issue by BelinChung** [vue-bulma/modal#1]
正文用中文好了
有些情况下，modal body里面的内容可能是需要预编译的 vue 模板，这时候如果能支持传入一个 partial 作为 modal body 可用性就更高了

这只是一个简单可用的commit，因为我只用到了 card modal，就不发 PR 了。建议对整个 modal 组件做一个可复用的变更。
https://github.com/BelinChung/modal/commit/88ad34a18fbf6cf70acbc2ff3f24de931b711c59

**Comment by fundon** [comment]
@BelinChung 感谢反馈和建议。

好的，会对这块进行优化和可复用更新

**Comment by fundon** [comment]
@BelinChung Vue 2.0 不支持 `partial` 了
