### ISSUE TITLE
Failed to compile on 'npm run production'

### ISSUE THREAD

**Issue by dukadin** [vue-bulma/modal#17]
I am using laravel-mix and Webpack.

```
public/js/app.js from UglifyJs
Unexpected token punc «(», expected punc «:» [./~/vue-bulma-modal/src/BaseModal.js:14,0][public/js/app.js:656,7]
```

**Comment by a-zog** [comment]
Having the same issue, any update ?

**Comment by dukadin** [comment]
Nope. I wrote Modal component by myself.

**Comment by a-zog** [comment]
I'm using this component to save time, but I will do it myself too.
Thank you for the answer anyway
