### ISSUE TITLE
[FEATURE REQUEST] slot for footer in CardModal

### ISSUE THREAD

**Issue by darkylmnx** [vue-bulma/modal#18]
it would be very useful to have a slot for the footer in the card modal, because sometimes i do not need the two buttons and sometimes i even need more buttons or something else but the footer is not configurable.

A simple slot would be easy to implement and therefore, the events emited for these buttons won't be needed anymore, as it would be handled by the wya this slot would be use

**Comment by DisruptiveMind** [comment]
@darkylmnx hopefully #24 serves your needs. It helped me.
