### ISSUE TITLE
Component wont transpile during build

### ISSUE THREAD

**Issue by D3m1urg0** [vue-bulma/modal#19]
the shortand functions inside the .js file imported as a mixin (BaseModal.js):

es. `data()`

wont be transpiled ( in `data: function()`) when i build the app with webpack

this gives error on ie 11 or lower

**Comment by mcknight0219** [comment]
Have you traced to where the issue is ? I had similar issue when using webpacker in Rails. Babel plugin wouldn't transpile.

**Comment by mrchimp** [comment]
I'm having the same problem using Laravel Mix.

**Comment by ghost** [comment]
sis you checked your Webpack.base.conf ?   is the babel-loader excluding /node_modules from compiling.?  in which case , add the node_module/vue-bulma-modal file path into the include...
