### ISSUE TITLE
UNMET PEER DEPENDENCY sinon@1.17.7

### ISSUE THREAD

**Issue by adewaleafolabi** [vue-bulma/modal#22]
Am trying to use vue-bulma-modal but keep getting the error unmet peer dependency 

```
npm install vue-bulma-modal --save

+-- UNMET PEER DEPENDENCY sinon@1.17.7
`-- vue-bulma-modal@1.0.1 

```

```
npm install npm install sinon@1.17.7

+-- install@0.10.1 
+-- npm@4.6.1 
`-- UNMET PEER DEPENDENCY sinon@1.17.7

```

**Comment by OmgImAlexis** [comment]
Peer deps aren't required, that's a warning not an error.

**Comment by lben** [comment]
I am unable to use bulma as well unless I import it from the cdn. When I try to install it I get the same warnings and the bulma css dont get applied. If i use the cdn everything works fine.
