### ISSUE TITLE
Modal flickering

### ISSUE THREAD

**Issue by StarpTech** [vue-bulma/modal#6]
Hi, when I open the modal the transition between `.modal <-> .is-active` leads to flicker effect.
I have to set also the enter class to avoid this issue. Do you have an idea why this is necessary? I try it like in the example. In vue-admin you create the modal in a different way.

```
:enter-class="enterClass"
```

**Comment by StarpTech** [comment]
According to the changes https://github.com/vuejs/vue/releases/tag/v2.1.7
In Vuejs 2.1.7 the transition component was changed.

> When fixing #4510 (ensure leave transitions and enter transitions triggered by the same state change are started in the same frame), we had to move the application of the v-enter-active and v-leave-active classes to one frame after the application of v-enter and v-leave.

[Example](https://github.com/vuejs/vue/blob/dev/examples/move-animations/index.html#L18-L31)

**Comment by fundon** [comment]
Thank you. Try vue 2.1.8.
